### ISSUE TITLE
build-wlan-ap是私人仓库么，想参考一下代码

### ISSUE THREAD

**Issue by DoveKi** [JiaY-shi/wlan-ap-build#1]
最新Telecominfraproject的qsdk分支5.4配置文件好像有改变，想参考一下大佬的代码🥺

**Comment by JiaY-shi** [comment]
`#!/bin/bash


CRTDIR=$(pwd)

base=$1
profile=$2

if [ ! -e "$base" ]; then
	echo "Please enter base folder"
	exit 1
else
	if [ ! -d $base ]; then 
		echo "Openwrt base folder not exist"
		exit 1
	fi
fi

if [ ! -n "$profile" ]; then
	profile=glinet_ax1800
fi

echo "Start..."

#clone source
git clone -b staging-qsdk-ath12 https://github.com/Telecominfraproject/wlan-ap.git $base/wlan-ap
cd $base/wlan-ap
git am $CRTDIR/patches/*.patch

# cp some files
cd $CRTDIR
cp -r custom/ $base/wlan-ap/feeds/custom/
cp -rf *.yml $base/wlan-ap/profiles/

# copy path
cp -r patches/openwrt/*.patch $base/wlan-ap/patches/ipq807x/

# setup
cd $base/wlan-ap
$base/wlan-ap/setup.py --setup

#gen config
cd $base/wlan-ap/openwrt
./scripts/gen_config.py $profile

# feed update
./scripts/feeds update -a 
./scripts/feeds install -a
make defconfig

echo "CONFIG_KERNEL_IPQ_MEM_PROFILE=512" >> .config
echo "CONFIG_IPQ_MEM_PROFILE=512"  >> .config

`
@DoveKi build.sh 脚本核心代码，私库里主要是包含了一些自定义的配置，就没有开放

**Comment by DoveKi** [comment]
谢谢大佬，那dts部分不需要修改么，我看官方之前5.4的commit是给v7 的32位5.4老源码

**Comment by DoveKi** [comment]
>

**Comment by JiaY-shi** [comment]
目前不用，你可以把官方5.4下的几个补丁给打了，目前我用了一段时间了，没啥问题，就是内存不太够了 @DoveKi

**Comment by DoveKi** [comment]
> 目前不用，你可以把官方5.4下的几个补丁给打了，目前我用了一段时间了，没啥问题，就是内存不太够了 @DoveKi

谢谢老哥 我晚点试试看
